baseURL = "https://kelvinmaina.me/"
languageCode = "en-us"
publishDir = "docs"
theme = "aafu"
[build]
  writeStats = true

[params]
    title = "KELVIN MAINA WANGARI"
    author = "Kelvin Maina" # Keep as is, or use "Kelvin Maina Wangari" [cite: 2, 55]
    description = "Kelvin Maina Wangari's Personal Website" # Updated description
    copyright = "© 2025 Kelvin Maina Wangari" # Updated copyright

    [params.theme]
        # Available themes are 'light', 'dark', 'ocean', and 'pinkish'
        mainTheme = "ocean"
        # setting false below will hide 'aafu by darshan' displayed under the profile pic
        showAttribute = true
        singlePage = false

    [params.favicons]
        use = true
        metas = '''
        <link rel="apple-touch-icon" sizes="180x180" href="apple-touch-icon.png">
        <link rel="icon" type="image/png" sizes="32x32" href="favicon-32x32.png">
        <link rel="icon" type="image/png" sizes="16x16" href="favicon-16x16.png">
        <link rel="manifest" href="site.webmanifest">
        <link rel="mask-icon" href="safari-pinned-tab.svg" color="#252627">
        <link rel="shortcut icon" href="favicon.ico">
        '''

    # Profile section
    [params.profile]
        name = "Kelvin Maina Wangari" # Updated name [cite: 2, 55]
        tagline = "Head of ICT | Computer Science / ICT Teacher" # Updated tagline [cite: 3]
        location = "Hargeisa, Somaliland / Nairobi, Kenya" # Updated location [cite: 2]
        photo = "profile.jpg" # Keep placeholder image name

    # Section for links to social websites
    [params.social]
        title = "Links"

        [[params.social.list]]
            icon = "fab fa-linkedin-in"
            url = "https://www.linkedin.com/in/kelvin-maina-522877a4/"
            title = "LinkedIn"
        [[params.social.list]]
            icon = "fab fa-stack-overflow"
            url = "https://stackoverflow.com/users/12234952/kelvin-maina?tab=profile"
            title = "StackOverflow"
        [[params.social.list]]
            icon = "fab fa-github"
            url = "https://github.com/KelvinMW" # Found in document [cite: 20]
            title = "GitHub"
        [[params.social.list]]
            icon = "fab fa-twitter"
            url = "https://twitter.com/MKelvinW"
            title = "Twitter"
        # Add email from document if desired
        # [[params.social.list]]
        #     icon = "fas fa-envelope"
        #     url = "mailto:wkelvinmaina@gmail.com" # Email from document [cite: 2]
        #     title = "Email"

    #Specify what is showin in the Accordion
    [[params.showInAccordion]]
        item = "aboutme"
        expand = true  # true for the section that is initially expanded
    [[params.showInAccordion]]
        item = "experience"
    [[params.showInAccordion]]
        item = "education"
    [[params.showInAccordion]]
        item = "publication" # No publications found in doc [cite: 1]
    [[params.showInAccordion]]
        item = "project"
    [[params.showInAccordion]]
        item = "skill"
    [[params.showInAccordion]]
        item = "hobby" # No hobbies found in doc [cite: 1]

    [params.aboutme]
        title = "About Me"
        icon = "fas fa-user"
        description = '''### About Me
I am a multifaceted professional with a strong background in computer science, IT consultancy, and education[cite: 17, 25]. With a Bachelor's degree in Computer Science and Mathematics from Jomo Kenyatta University of Agriculture & Technology and a Diploma in Technical Teacher Education (Advanced) from Kenya Technical Trainers College, my career has been dedicated to merging the realms of technology and education[cite: 12, 25].

In the IT sector, I have extensive experience as a software developer and IT consultant, collaborating with companies like Kwality Consulting Solutions to design and implement client-specific software solutions[cite: 35]. My expertise includes managing cloud server deployments, enhancing user engagement through innovative features, and conducting comprehensive business analyses to drive decision-making.

As a teacher, I have over six years of experience inspiring and motivating students from diverse backgrounds[cite: 17]. My teaching philosophy emphasizes hands-on, project-based learning, and I strive to create an inclusive and engaging classroom environment[cite: 18]. This approach fosters creativity, critical thinking, and collaboration, empowering the next generation of computer scientists[cite: 22]. In my free time, I enjoy staying updated with the latest trends in technology and engaging in community service projects[cite: 29]. I am passionate about mentoring young aspiring computer scientists and continuously seek to bridge the gap between technology and education to make meaningful contributions to society[cite: 22].
''' # Kept provided description and added citations

    # Experience section
    [params.experience]
        title = "Experiences"
        icon = "fas fa-briefcase"

        [[params.experience.list]]
            position = "Head of ICT | Computer Science / ICT Teacher" [cite: 3]
            dates = "August 2018 - *Present*" [cite: 4] # Assuming present based on context
            company = "ELM International School, Hargeisa, Somaliland" [cite: 2]
            details = """
**Teaching Roles:** [cite: 6]
* Deliver engaging IGCSE/A-Level Computer Science/ICT curriculum (Theory & Practical: Database, Programming, Office Skills, Web Authoring)[cite: 6, 7, 17].
* Design lesson plans, assignments, projects; assess student work and provide feedback[cite: 7].
* Prepare candidates for IGCSE exams[cite: 7].
* Manage classroom to encourage participation and maintain a positive learning environment[cite: 7].
* Promote digital literacy to staff and public (e.g., via MOOCs)[cite: 7].

**Head of ICT Roles:** [cite: 7]
* Oversee school's technology integration to align with vision and goals[cite: 7, 8].
* Lead the ICT department[cite: 8].
* Engage in strategic planning for technology use[cite: 8].
* Develop and improve ICT curriculum[cite: 8].
* Train staff on collaboration tools and technology integration[cite: 8, 24].
* Manage school data policy and data protection compliance[cite: 8].
""" # Summarized from duties [cite: 5, 6, 7, 8]

    # Education section
    [params.education]
        title = "Education"
        icon = "fas fa-graduation-cap"

        [[params.education.list]]
            degree = "Diploma in Technical Teacher Education (Advanced)" [cite: 12]
            college = "Kenya Technical Trainers College" [cite: 12]
            dates = "April 2018 - Aug 2019" [cite: 12]
            # No thesis mentioned for diploma [cite: 12]
            # thesis_title = ""
            # thesis_url = "#"
        [[params.education.list]]
            degree = "Bachelor of Science [degree] Mathematics & Computer Science" [cite: 12]
            college = "Jomo Kenyatta University of Agriculture & Technology" [cite: 12]
            dates = "Aug 2012 - Nov 2016" [cite: 12]
            # No thesis mentioned for bachelor's [cite: 12]
            # thesis_title = ""
            # thesis_url = "#"
        [[params.education.list]]
            degree = "Secondary School Diploma" [cite: 13]
            college = "St. Michael’s Secondary School" [cite: 13]
            dates = "Jan 2008 - Dec 2011" [cite: 13]

    # Publication section
    [params.publication]
        title = "Publications"
        icon = "fas fa-book"
        # No publications listed in the source document[cite: 1]. Keeping placeholders commented out.
        # format = ["date", "authors", "title", "journal"]
        # types = ["Journal Articles", "Proceedings"]
        # [[params.publication.list]]
        #     title = "..."
        #     authors = "..."
        #     date = "..."
        #     journal = "..."
        #     url = "#"
        #     type = "Journal Articles"

    # Project section
    [params.project]
        title = "Projects"
        icon = "fas fa-project-diagram"

        [[params.project.list]]
            title = "MOOCs for Secondary Students" [cite: 19]
            url = "https://secondary.elmischools.com/index.php?q=%2Fmodules%2FFree+Learning%2Funits_browse.php&view=grid&gibbonDepartmentID=11&difficulty=&name=&Go=Go" [cite: 19]
            description = "Created Massive Open Online Courses (MOOCs) to supplement classroom learning, fostering independent study and digital literacy for secondary students." [cite: 19]
        [[params.project.list]]
            title = "GitHub Projects" [cite: 20]
            url = "https://github.com/kelvinMW/" [cite: 20]
            description = "Developed real-world projects hosted on GitHub, demonstrating practical application of computer science concepts." [cite: 20]
        [[params.project.list]]
            title = "ELM Schools Android App" [cite: 21]
            url = "https://play.google.com/store/apps/details?id=com.elmischools.system" [cite: 21]
            description = "Contributed to the development of the ELM Schools Android application available on Google Play." [cite: 21]
        [[params.project.list]]
            title = "Extracurricular Tech Initiatives" [cite: 22]
            # url = "#" # No specific URL provided
            description = "Mentored students in extracurricular tech initiatives like coding competitions and robotics clubs." [cite: 22]

    # Skill section
    [params.skill]
        title = "Skills"
        panelId = "skill-panel"
        icon = "fas fa-cogs"
        # Ratings are not provided in the document[cite: 1].

        [[params.skill.list]]
            skill = "ICT/Computer Science Teaching (KS3-KS5, IGCSE/A-Level)" [cite: 17]
            # skillrating = 90 # Rating not available
        [[params.skill.list]]
            skill = "Curriculum Design, Delivery & Assessment" [cite: 17]
            # skillrating = 90 # Rating not available
        [[params.skill.list]]
            skill = "Lesson Planning (Hands-on, Project-based)" [cite: 7, 18]
            # skillrating = 85 # Rating not available
        [[params.skill.list]]
            skill = "Classroom Management" [cite: 7]
            # skillrating = 80 # Rating not available
        [[params.skill.list]]
            skill = "Database, Programming, Algorithm Design, Web Authoring, Office Productivity" [cite: 7]
            # skillrating = 80 # Rating not available
        [[params.skill.list]]
            skill = "MOOC Creation & Digital Literacy Promotion" [cite: 7, 19]
            # skillrating = 75 # Rating not available
        [[params.skill.list]]
            skill = "ICT Department Leadership & Strategic Planning" [cite: 8, 23]
            # skillrating = 85 # Rating not available
        [[params.skill.list]]
            skill = "Staff Training (Collaboration Tools, Blended Learning)" [cite: 8, 24]
            # skillrating = 80 # Rating not available
        [[params.skill.list]]
            skill = "Data Policy & Protection Compliance" [cite: 8]
            # skillrating = 70 # Rating not available
        [[params.skill.list]]
            skill = "Software Development & IT Consultancy" # Implied from About Me
            # skillrating = 70 # Rating not available
        [[params.skill.list]]
            skill = "Communication, Presentation & Mentoring" [cite: 22, 26]
            # skillrating = 85 # Rating not available
        [[params.skill.list]]
            skill = "Organization & Adaptability" [cite: 27, 28]
            # skillrating = 80 # Rating not available
        [[params.skill.list]]
            skill = "Researching Emerging Technologies" [cite: 29]
            # skillrating = 75 # Rating not available

    # Hobby section
    [params.hobby]
        title = "Hobbies"
        icon = "fas fa-gamepad"
        # No specific hobbies mentioned in the document[cite: 1]. Keeping placeholders.
        [[params.hobby.list]]
            hobby = "Staying updated with technology trends" [cite: 29] # Inferred from About Me
        [[params.hobby.list]]
            hobby = "Community service projects" # Inferred from About Me
        [[params.hobby.list]]
            hobby = "Mentoring young computer scientists" [cite: 22] # Inferred from About Me